name: Scrape Exophase

on:
  # remove between the lines to disable the schedule
  schedule:
    - cron: "23 4 * * *"  # daily at 04:23 UTC
  # remove between the lines to disable the schedule
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run scraper
        run: |
          python scrape_exophase.py

      - name: Embed JSON in HTML
        run: |
          python embed_json.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        shell: bash
        run: |
          set -euo pipefail
          if ! git diff --quiet || [ -n "$(git ls-files --others --exclude-standard)" ]; then
            git add games.json games_viewer_embedded.html
            git commit -m "chore: update games.json and embedded HTML [skip ci]" || echo "Nothing to commit"
            git push
          else
            echo "No changes to commit."
          fi
