name: Scrape Exophase

on:
  schedule:
    - cron: "23 4 * * *"  # daily at 04:23 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run scraper
        run: |
          python scrape_exophase.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git add games.csv
            git commit -m "chore: update games.csv [skip ci]"
            git push
          else
            echo "No changes to commit."
